### ISSUE TITLE
requirements.txt not comaptible with Python 3.8

### ISSUE THREAD

**Issue by marconius** [balena-io/support-shift-scheduler#9]
I noticed this when trying to install the requirements in a Python 3.8 env and getting that the `ortools` dependency could not be satisfied. [PyPI](https://pypi.org/project/ortools/#files) shows that there is indeed no package for 3.8. The lack of support by ortools would not be an issue really, if the [Requirements section in the project's README](https://github.com/balena-io/support-shift-scheduler#requirements) reflected it.

Hope this saves someone a bit of time going forward.

**Comment by AlidaOdendaal** [comment]
Thanks for raising this @marconius ! `ortools` now supports Python 3.8 as well.
